title               : Rhecipies

collections:
  posts:
    output          : true
    permalink       : /:collection/:title
    directory       : _posts
  cuisines:
    output          : true
    permalink       : /:collection/:title
    directory       : _cuisines

defaults:
  - scope:
      path: ""
      type: "cuisines"
    values:
      layout: "cuisine"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - assets/js/*

include:
  - assets/js/anijs-min.js
  - assets/js/bundle.js
  - assets/js/search.js

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed