collections:
  cuisines:
    output: true

defaults:
  - scope:
      path: ""
      type: "cuisines"
    values:
      layout: "cuisine"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: [README.md]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed